# Change these first
owner: jonesyriffic # Your GitHub organization or username, where this repository lives
repo: gsp-peacock # The name of this repository

sites:
  - name: Peacock
    url: https://www.peacocktv.com/help

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /gsp-peacock
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: GSP Customer Management Uptime
  introTitle: Peacock Uptime
  navbar:
    - title: EU
      href: https://jonesyriffic.github.io/gsp-eu/
    - title: Peacock
      href: /
    - title: SST
      href: https://jonesyriffic.github.io/gsp-sst/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
